### PR TITLE
Glossarist v2 enhancements and fixes

### LINKED ISSUE #82: Operations on the Concept class: How to add a note? How to add a designation?
Operations on the Concept class: How to add a note? How to add a designation?

Need corresponding methods.

### LINKED ISSUE #84: `ManagedCollection#save_to_files` method does not save in the new Glossarist dataset format
Per https://github.com/glossarist/termium/issues/3 :

As described by @HassanAkbar  https://github.com/glossarist/glossarist-ruby/issues/83#issuecomment-1816447057

> we need 2 folders for creating a concept dataset (both folder names are singular)
> 
> * concept
> * localized_concept

In this line: 
https://github.com/glossarist/termium/blob/4b7ce29a7e0199f9766d0027cd081441fd9e2f97/lib/termium/cli.rb#L58

Clearly the `ManagedCollection#save_to_files` method in Glossarist does not export a Concept YAML folder that conforms to this concept dataset description.

Instead it exports to a flat directory structure where the universal concept and the localized concepts are within the same file.

`sources/concepts` in iso-iec-2382 repo ([link](https://github.com/metanorma/iso-iec-2382/tree/main/sources/concepts)):
```
concept-10031778.yaml
concept-10031781.yaml
concept-2120533.yaml
concept-2120534.yaml
...
```

`concept-2120533.yaml`:
```yaml
---
termid: '2120533'
term: network
eng:
  id: '2120533'
  terms:
  - type: expression
  # ...
  definition:
  - content: arrangement of entities and their interconnections
  # ...
fre:
  id: '2120533'
  terms:
  - type: expression
  # ...
```

This task is to update the method so that it exports a Glossarist dataset that is immediately useable by Geolexica.

### PR DESCRIPTION
**Pull request by HassanAkbar**
- added methods to add single `note` and `designation`
- updated `save_to_files` to save in Glossarist V2 Format

closes #82 
closes #84

### CODE REVIEW

**Comment by ronaldtse** [comment]
@HassanAkbar thanks for this! Could you please try:

1. Using the newly created functionality to [migrate the iso-iec-2382 collection](https://github.com/metanorma/iso-iec-2382#extracting-terms-from-the-termium-plus-export)
2. Try loading the dataset in Glossarist
?

This is related to this task:
* https://github.com/metanorma/iso-iec-2382/issues/5

**Review by ronaldtse — CHANGES_REQUESTED** [review]
Failed to run.

**Comment by ronaldtse** [comment]
At the iso-iec-2382 repository:

```sh
$ bundle exec termium convert -i reference-docs/xml/ISO-IEC_2382.xml -o sources/concepts
Reading TERMIUM export file: reference-docs/xml/ISO-IEC_2382.xml
Size of TERMIUM dataset: 3263
Converting to Glossarist...
Using existing directory: sources/concepts
Writing Glossarist dataset to: sources/concepts
bundler: failed to load command: termium (/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bin/termium)
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/glossarist-ruby-915cf0005a43/lib/glossarist/concept_manager.rb:64:in `save_concept_to_file': undefined method `each' for nil:NilClass (NoMethodError)

      concept.localized_concepts.each do |lang, uuid|
                                ^^^^^
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/glossarist-ruby-915cf0005a43/lib/glossarist/concept_manager.rb:32:in `each_value'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/glossarist-ruby-915cf0005a43/lib/glossarist/concept_manager.rb:32:in `save_to_files'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/glossarist-ruby-915cf0005a43/lib/glossarist/managed_concept_collection.rb:76:in `save_to_files'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/termium-0.1.2/lib/termium/cli.rb:58:in `convert'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
```

**Comment by HassanAkbar** [comment]
@ronaldtse created a new issue for this change here -> https://github.com/metanorma/metanorma-plugin-glossarist/issues/20

**Pull request merged**
