### PR TITLE
feat: adding group to localized concept

### LINKED ISSUE #59: Add `group` key to localized_concept
It would be best to update the Glossarist gem and associated gems to allow the `group` key (it should take an array of "groups"). There are many foreseeable uses of it.

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-10303-2/issues/133#issuecomment-1525256654_

### PR DESCRIPTION
**Pull request by HassanAkbar**
Update `Glossarist` gem to allow the `group` key (it should take an array of "groups").

closes #59

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse would it make more sense to move the `group` outside the `localization` or is it ok to have a separate group array for each `localized concept`?

**Comment by ronaldtse** [comment]
Maybe at the concept level for now.

**Comment by HassanAkbar** [comment]
> Maybe at the concept level for now.

That means one group per concept and not per translation. Right?

**Comment by ronaldtse** [comment]
> That means one group per concept and not per translation. Right?

Yes.

**Pull request merged**
