### PR TITLE
updated the yaml format

### PR DESCRIPTION
**Pull request by HassanAkbar**
Updated the yaml format for abbreviation

### CODE REVIEW

**Comment by ronaldtse** [comment]
@HassanAkbar there is a subtlety here. 

There are a few kinds of "abbreviations" ("Abbreviated term resulting from the omission of some of its letters.").

See this: https://www.iso.org/obp/ui/#iso:std:iso:4:ed-3:v1:en

These are the kinds:
* acronym (Abbreviated complex term made up of letters from the full form of a term and strung together into a sequence pronounced only syllabically)
* initialism (Abbreviated complex term or name made up of the first letters of the term elements.)
* truncation(Shortening of a word by the omission of two or more continuous letters at the end.)
* other (something that doesn't fit into the above categories)

This is why an "abbreviation" has several types.

**Review by ronaldtse — APPROVED** [review]
Accepting for now.

**Comment by HassanAkbar** [comment]
@ronaldtse We have all of these types in glossarist here (https://github.com/glossarist/glossarist-ruby/blob/main/config.yml#L47-L51), so we can set the type to `abbreviation` and set if it is an `acronym` or `initialism` etc like

```yaml
- type: abbreviation
  initialism: true
  designation: something
```

OR

```yaml
- type: abbreviation
  truncation: true
  designation: something
```

 and for `others` we can leave it just to 

```yaml
- type: abbreviation
  designation: something
```

**Comment by ronaldtse** [comment]
Got it @HassanAkbar , thank you for the explanation. Can you add some documentation for the YAML format? I think we should really use YAML Schema to describe the Glossarist YAML format.

**Comment by HassanAkbar** [comment]
@ronaldtse Sure, I'll update the documentation after the `iso-10303-2` task. I've created and issue for that here https://github.com/glossarist/glossarist-ruby/issues/65

**Pull request merged**
